# version: '3.8'
services:
  edusmart-api:
    container_name: edusmart-api
    restart: always
    image: node:22.11.0
    environment:
      - PORT_API=4007
      - CLOUDINARY_CLOUD_NAME=ddm1vx7zq
      - CLOUDINARY_API_KEY=444682295139813
      - CLOUDINARY_API_SECRET=7EwpxqbOWpDfVTe_u9uty_Jdho0
    ports:
      - 3007:4007
    volumes:
      - ./:/usr/src/edusmart
    working_dir: /usr/src/edusmart

    networks:
      - monorepo-network
    # for production
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

networks:
  monorepo-network:
    driver: bridge

# edusmart-react: localhost: 5173 => container: 4006
# edusmart-api: localhost: 3007 => container: 4007
# edusmart-batch: localhost: 3008 => container: 4008

# docker compose up -d
# docker-compose start
# docker-compose stop
# docker-compose restart
# docker-compose stop && docker compose rm -f
